### ISSUE TITLE
download from 'https://api.github.com/repos/NMikolajewicz/scMiko/tarball/HEAD' failed

### ISSUE THREAD

**Issue by gt7901b** [NMikolajewicz/scMiko#1]
Hi, 

I ran  devtools::install_github(repo = "NMikolajewicz/scMiko")
but got the error message

Downloading GitHub repo NMikolajewicz/scMiko@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/NMikolajewicz/scMiko/tarball/HEAD' failed

I

**Comment by NMikolajewicz** [comment]
@gt7901b  Can you try downloading the package again? The demo datasets may have been causing the package to be bloated leading to the installation to time out. Give it a try again and please let me know if you encounter any further issues. Thanks

**Comment by gt7901b** [comment]
sorry, still have issue.

ERROR: dependency ‘presto’ is not available for package ‘scMiko’
* removing ‘/Users/xxxxx/Library/R/x86_64/4.1/library/scMiko’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/1m/ff4p2m5j19sb533npkqlxjsr0000gp/T//Rtmp98qEKa/file8c715f313070/scMiko_0.1.0.tar.gz’ had non-zero exit status

**Comment by NMikolajewicz** [comment]
Unfortunately **presto** is not available on CRAN, you will have to download it directly from the github repository: https://github.com/immunogenomics/presto

**Comment by gt7901b** [comment]
yes. installed presto and now it worked
