### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by royfrancis** [NMikolajewicz/scMiko#2]
Tried installing from Github.

```
> remotes::install_github("NMikolajewicz/scMiko")
Downloading GitHub repo NMikolajewicz/scMiko@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/NMikolajewicz/scMiko/tarball/HEAD' failed
```

Then I tried to download and install it locally.
```

> install.packages("~/Downloads/scMiko-master.zip", repos = NULL, type = "win.binary")
Error in install.packages : cannot install Windows binary packages on this platform
```

R version 4.1.0 (2021-05-18)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

**Comment by NMikolajewicz** [comment]
Unfortunately I don't know how to address this error... perhaps try downloading the package as a .zip file and installing it locally. See below  for steps on how to download the package zip file:

![zip_download](https://user-images.githubusercontent.com/46906473/192153923-72119b16-0fb8-477f-a1f9-c687aa9f872c.jpg)

Let me know if you continue to have an issue with this.

**Comment by lyuguol** [comment]
> Tried installing from Github.
> 
> ```
> > remotes::install_github("NMikolajewicz/scMiko")
> Downloading GitHub repo NMikolajewicz/scMiko@HEAD
> Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
>   download from 'https://api.github.com/repos/NMikolajewicz/scMiko/tarball/HEAD' failed
> ```
> 
> Then I tried to download and install it locally.
> 
> ```
> 
> > install.packages("~/Downloads/scMiko-master.zip", repos = NULL, type = "win.binary")
> Error in install.packages : cannot install Windows binary packages on this platform
> ```
> 
> R version 4.1.0 (2021-05-18) Platform: x86_64-conda-linux-gnu (64-bit) Running under: Ubuntu 20.04.4 LTS

@royfrancis Hello royfrancis, did you check (i) whether all the 'dependency' have been installed; (ii) all the packages are up to date? 

Good luck.

Guoliang

**Comment by NMikolajewicz** [comment]
@royfrancis I have a solution for you. I believe the issue is related to the installation timing out. Try increasing the timeout time prior to installing the package:

`options(timeout=300)`

and then run

`devtools::install_github(repo = "NMikolajewicz/scMiko")`

Please let me know if that solves the issue for you.

**Comment by emanuelavilla** [comment]
Hello! 

I have the same issue. I tried increasing the timeout as your suggestion, but it doesn't work anyway.

> @royfrancis I have a solution for you. I believe the issue is related to the installation timing out. Try increasing the timeout time prior to installing the package:
> 
> `options(timeout=300)`
> 
> and then run
> 
> `devtools::install_github(repo = "NMikolajewicz/scMiko")`
> 
> Please let me know if that solves the issue for you.

**Comment by royfrancis** [comment]
Coming back to this after a few months. I tried the installation again and it seems to work this time. I had to install one of the dependency packages manually (`devtools::install_github("immunogenomics/presto")`). I also upgraded OS from Ubuntu 20.04 to 22.04. There could be many other things that might have changed on my system. I don't know for sure. 
I didn't have any timeout issues, but it does take some time for the installation to get started. Maybe this repo is quite large?

**Comment by NMikolajewicz** [comment]
The repo is quite large (currently ~700 mb) so this can certainly be contributing to those prolonged installations. I'm looking into trimming the size down in future versions.

**Comment by mdidish** [comment]
Hello, I had the same problem than @royfrancis, even with Ubuntu 22.04.

But you can install locally after downloading the zip version as shown by @NMikolajewicz.
To avoid
```
> install.packages("~/Downloads/scMiko-master.zip", repos = NULL, type = "win.binary")
Error in install.packages : cannot install Windows binary packages on this platform
```

You just need to convert the zip file to tar.gz file.
After the first try you will see which dependencies you need to install:
```
> install.packages("~/scMiko-master.tar.gz", repos = NULL, type = "source")
Installation du package dans ‘/home/marc/R/x86_64-pc-linux-gnu-library/4.3’
(car ‘lib’ n'est pas spécifié)
ERROR: dependencies ‘flexdashboard’, ‘ggpmisc’, ‘ggExtra’ are not available for package ‘scMiko’
```
So install these dependencies, then you can install the package `install.packages("~/scMiko-master.tar.gz", repos = NULL, type = "source")`.

Best,
