### ISSUE TITLE
know a good mitochondrial threshold a priori is not always possible 

### ISSUE THREAD

**Issue by emanuelavilla** [NMikolajewicz/scMiko#4]
Hello Dr. Mikolajewicz!

A very nice and useful tool for single-cell! Thanks!

I have a question: did you consider using tools, such as miQC developed by the Greene Laboratory at the University of Colorado Anschutz, for mitochondrial quality control?

What I mean is that using an arbitrary threshold could eliminate cells that are actually good. Accordingly, recent work has shown these thresholds can be highly dependent on the organism or tissue, the type of scRNA-seq technology used, or the protocol-specific decisions made as part of the disassociation, library preparation, and sequencing steps (Osorio D, Cai JJ. Systematic determination of the mitochondrial proportion in human and mice tissues for single-cell RNA-sequencing data quality control. Bioinformatics. 2020).

**Comment by NMikolajewicz** [comment]
Thank you for your thoughtful feedback. I agree that having a more adaptive threshold would be advantageous, as our group has also seen that the optimal threshold can vary between 10-60%, depending on the cell line/tissue type. Currently the threshold is manually set, but I will look into having a more adaptive approach to selecting the threshold in future versions. Thank you for the paper that you shared.
